# Generated by Django 4.1.7 on 2023-03-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_alter_crypto_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto',
            options={'verbose_name': 'Криптовалюту', 'verbose_name_plural': 'Криптовалюта'},
        ),
        migrations.AlterField(
            model_name='crypto',
            name='code',
            field=models.CharField(max_length=60, unique=True, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='current_rate',
            field=models.CharField(max_length=60, verbose_name='Текущий курс в USD'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Имя'),
        ),
    ]
