# Generated by Django 4.1.7 on 2023-03-23 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coin', '0003_alter_crypto_options_alter_crypto_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptos', models.ManyToManyField(to='coin.crypto', verbose_name='Избранные криптовалюты')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Избранные криптовалюты пользователя',
                'verbose_name_plural': 'Избранные криптовалюты пользователей',
            },
        ),
    ]
