# Generated by Django 4.1.7 on 2023-04-21 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='cryptos',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('crypto', models.ManyToManyField(through='coin.Favorites', to='coin.crypto')),
            ],
        ),
        migrations.AddField(
            model_name='favorites',
            name='cryptos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coin.crypto', verbose_name='Избранные криптовалюты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='coin.profile', verbose_name='Имя пользователя'),
        ),
    ]
